extends RefCounted

const DiveSessionScript := preload("res://scripts/dive_session.gd")
const ProgressionStateScript := preload("res://scripts/progression_state.gd")
const SurvivalStateScript := preload("res://scripts/survival_state.gd")
const SpawnPointScript := preload("res://scripts/spawn_point.gd")
const UpgradePurchaseScript := preload("res://scripts/upgrade_purchase.gd")
const DiveCapacityServiceScript := preload("res://scripts/services/dive_capacity_service.gd")
const DiveToolActionServiceScript := preload("res://scripts/services/dive_tool_action_service.gd")
const ScanTargetResolverScript := preload("res://scripts/scan_target_resolver.gd")
const SpawnSelectionScript := preload("res://scripts/spawn_selection.gd")
const PlayerScript := preload("res://scripts/player.gd")
const PlayerScene := preload("res://scenes/Player.tscn")
const MainScene := preload("res://scenes/Main.tscn")
const ReadabilityMarkerPatternsScript := preload("res://scripts/readability_marker_patterns.gd")
const ScanPulseVisualScript := preload("res://scripts/scan_pulse_visual.gd")
const ExpeditionGoalFormatterScript := preload("res://scripts/expedition_goal_formatter.gd")
const ExpeditionConditionScript := preload("res://scripts/expedition_condition.gd")
const MainScript := preload("res://scripts/main.gd")
const Area01SourceMapOverlayScript := preload("res://scripts/area01_source_map_overlay.gd")
const Area01BlockoutBuilderScript := preload("res://scripts/area01_blockout_builder.gd")
const Area01SourceTruthValidatorScript := preload("res://scripts/area01_source_truth_validator.gd")
const Area01VisualCueContractScript := preload("res://scripts/area01_visual_cue_contract.gd")
const Area01VisualDirectorScript := preload("res://scripts/area01_visual_director.gd")
const Area01VisualStagingServiceScript := preload("res://scripts/debug/area01_visual_staging_service.gd")
const BlackwaterVisualStagingServiceScript := preload("res://scripts/debug/blackwater_visual_staging_service.gd")
const BlueChimneyVisualStagingServiceScript := preload("res://scripts/debug/blue_chimney_visual_staging_service.gd")
const MobileTouchControlsScript := preload("res://scripts/mobile_touch_controls.gd")
const RunTelemetryResetServiceScript := preload("res://scripts/services/run_telemetry_reset_service.gd")
const ConditionPresenterScript := preload("res://scripts/ui/condition_presenter.gd")
const DaylightCargoVisualStagingServiceScript := preload("res://scripts/debug/daylight_cargo_visual_staging_service.gd")
const DaylightTimerHudServiceScript := preload("res://scripts/ui/daylight_timer_hud_service.gd")
const DepthRailServiceScript := preload("res://scripts/ui/depth_rail_service.gd")
const DiscoveryNamePresenterScript := preload("res://scripts/ui/discovery_name_presenter.gd")
const DuskTrenchVisualStagingServiceScript := preload("res://scripts/debug/dusk_trench_visual_staging_service.gd")
const ExpeditionSlateNodeServiceScript := preload("res://scripts/ui/expedition_slate_node_service.gd")
const ExpeditionSlatePresenterScript := preload("res://scripts/ui/expedition_slate_presenter.gd")
const ExpandedRouteVisualStagingServiceScript := preload("res://scripts/debug/expanded_route_visual_staging_service.gd")
const HealthFeedbackPresenterScript := preload("res://scripts/ui/health_feedback_presenter.gd")
const HealthFeedbackServiceScript := preload("res://scripts/ui/health_feedback_service.gd")
const HealthDamageVisualStagingServiceScript := preload("res://scripts/debug/health_damage_visual_staging_service.gd")
const HollowReefVisualStagingServiceScript := preload("res://scripts/debug/hollow_reef_visual_staging_service.gd")
const HudPromptPresenterScript := preload("res://scripts/ui/hud_prompt_presenter.gd")
const HudPromptStateServiceScript := preload("res://scripts/ui/hud_prompt_state_service.gd")
const HudInstrumentBarServiceScript := preload("res://scripts/ui/hud_instrument_bar_service.gd")
const HudPresenterScript := preload("res://scripts/ui/hud_presenter.gd")
const BlackwaterGatePresenterScript := preload("res://scripts/ui/blackwater_gate_presenter.gd")
const HudLayoutServiceScript := preload("res://scripts/ui/hud_layout_service.gd")
const HudReferenceServiceScript := preload("res://scripts/ui/hud_reference_service.gd")
const SurfaceStatusPresenterScript := preload("res://scripts/ui/surface_status_presenter.gd")
const CargoSlotPresenterScript := preload("res://scripts/ui/cargo_slot_presenter.gd")
const HudVisibilityServiceScript := preload("res://scripts/ui/hud_visibility_service.gd")
const InventorySummaryPresenterScript := preload("res://scripts/ui/inventory_summary_presenter.gd")
const LowerConnectorVisualStagingServiceScript := preload("res://scripts/debug/lower_connector_visual_staging_service.gd")
const MirrorKelpVisualStagingServiceScript := preload("res://scripts/debug/mirror_kelp_visual_staging_service.gd")
const MinimapServiceScript := preload("res://scripts/ui/minimap_service.gd")
const NightBuildPresenterScript := preload("res://scripts/ui/night_build_presenter.gd")
const OpenHatchVisualStagingServiceScript := preload("res://scripts/debug/open_hatch_visual_staging_service.gd")
const OuterShelfVisualStagingServiceScript := preload("res://scripts/debug/outer_shelf_visual_staging_service.gd")
const OxygenFeedbackServiceScript := preload("res://scripts/ui/oxygen_feedback_service.gd")
const ResourcePresenterScript := preload("res://scripts/ui/resource_presenter.gd")
const ResourcePickupPresentationServiceScript := preload("res://scripts/ui/resource_pickup_presentation_service.gd")
const ResourceRoleVisualPresenterScript := preload("res://scripts/ui/resource_role_visual_presenter.gd")
const ResourceSummaryServiceScript := preload("res://scripts/ui/resource_summary_service.gd")
const RecentExpeditionLogServiceScript := preload("res://scripts/ui/recent_expedition_log_service.gd")
const RecentExpeditionPresenterScript := preload("res://scripts/ui/recent_expedition_presenter.gd")
const ScanEffectTextServiceScript := preload("res://scripts/ui/scan_effect_text_service.gd")
const ScanFeedbackPresenterScript := preload("res://scripts/ui/scan_feedback_presenter.gd")
const ScanTargetCardServiceScript := preload("res://scripts/ui/scan_target_card_service.gd")
const ScanTargetFeedbackServiceScript := preload("res://scripts/ui/scan_target_feedback_service.gd")
const SurfaceResultPresenterScript := preload("res://scripts/ui/surface_result_presenter.gd")
const SurfaceRunSummaryServiceScript := preload("res://scripts/ui/surface_run_summary_service.gd")
const SurvivalNeedSummaryServiceScript := preload("res://scripts/ui/survival_need_summary_service.gd")
const SurvivalSupplyCachePresenterScript := preload("res://scripts/ui/survival_supply_cache_presenter.gd")
const SurvivalSupplyCacheStateServiceScript := preload("res://scripts/ui/survival_supply_cache_state_service.gd")
const SurvivalNeedsPanelServiceScript := preload("res://scripts/ui/survival_needs_panel_service.gd")
const ToolBeltPresenterScript := preload("res://scripts/ui/tool_belt_presenter.gd")
const ToolBeltServiceScript := preload("res://scripts/ui/tool_belt_service.gd")
const RouteMemoryPresenterScript := preload("res://scripts/ui/route_memory_presenter.gd")
const RoutePresenterScript := preload("res://scripts/ui/route_presenter.gd")
const RouteProximityServiceScript := preload("res://scripts/services/route_proximity_service.gd")
const RouteSetupServiceScript := preload("res://scripts/services/route_setup_service.gd")
const SceneEventServiceScript := preload("res://scripts/services/scene_event_service.gd")
const SurvivalControllerServiceScript := preload("res://scripts/services/survival_controller_service.gd")
const RouteTimingCuePresenterScript := preload("res://scripts/ui/route_timing_cue_presenter.gd")
const RouteTimingCueServiceScript := preload("res://scripts/ui/route_timing_cue_service.gd")
const RunMemoryStateServiceScript := preload("res://scripts/ui/run_memory_state_service.gd")
const ResearchResultPresenterScript := preload("res://scripts/ui/research_result_presenter.gd")
const ResearchResultCalloutServiceScript := preload("res://scripts/ui/research_result_callout_service.gd")
const ConditionVisualSyncServiceScript := preload("res://scripts/ui/condition_visual_sync_service.gd")
const DiscoveryRevealSyncServiceScript := preload("res://scripts/ui/discovery_reveal_sync_service.gd")
const RouteGateSyncServiceScript := preload("res://scripts/ui/route_gate_sync_service.gd")
const RoutePayoffSyncServiceScript := preload("res://scripts/ui/route_payoff_sync_service.gd")
const RunPanelLayoutServiceScript := preload("res://scripts/ui/run_panel_layout_service.gd")
const RunPanelServiceScript := preload("res://scripts/ui/run_panel_service.gd")
const UpgradeCopyPresenterScript := preload("res://scripts/ui/upgrade_copy_presenter.gd")
const UpgradeMenuServiceScript := preload("res://scripts/ui/upgrade_menu_service.gd")
const UpgradeStateServiceScript := preload("res://scripts/ui/upgrade_state_service.gd")
const SaveServiceScript := preload("res://scripts/services/save_service.gd")
const VisualSmokeBridgeScript := preload("res://scripts/debug/visual_smoke_bridge.gd")
const ShipOffloadVisualStagingServiceScript := preload("res://scripts/debug/ship_offload_visual_staging_service.gd")
const SiltVeinVisualStagingServiceScript := preload("res://scripts/debug/silt_vein_visual_staging_service.gd")
const SurfaceOxygenVisualStagingServiceScript := preload("res://scripts/debug/surface_oxygen_visual_staging_service.gd")
const WideReefVisualStagingServiceScript := preload("res://scripts/debug/wide_reef_visual_staging_service.gd")
const WreckEchoVisualStagingServiceScript := preload("res://scripts/debug/wreck_echo_visual_staging_service.gd")
const ScannableScript := preload("res://scripts/scannable.gd")
const PredatorScript := preload("res://scripts/predator.gd")
const OxygenTankUpgrade := preload("res://resources/upgrades/oxygen_tank_1.tres")
const PressureSealUpgrade := preload("res://resources/upgrades/pressure_seal_1.tres")
const SignalLensUpgrade := preload("res://resources/upgrades/signal_lens_1.tres")
const EchoLensUpgrade := preload("res://resources/upgrades/echo_lens_1.tres")
const ResonanceKeyUpgrade := preload("res://resources/upgrades/resonance_key_1.tres")
const CargoRackUpgrade := preload("res://resources/upgrades/cargo_rack_1.tres")
const WaterFilterUpgrade := preload("res://resources/upgrades/water_filter_1.tres")
const PredatorWarningUpgrade := preload("res://resources/upgrades/predator_warning_1.tres")
const DecoyPulseUpgrade := preload("res://resources/upgrades/decoy_pulse_1.tres")
const SalvageCutterUpgrade := preload("res://resources/upgrades/salvage_cutter_1.tres")
const StarterResourceDefinitions := [
	preload("res://resources/driftwood.tres"),
	preload("res://resources/food_supply.tres"),
	preload("res://resources/glow_plankton.tres"),
	preload("res://resources/kelp_fiber.tres"),
	preload("res://resources/power_supply.tres"),
	preload("res://resources/quartz_glass.tres"),
	preload("res://resources/scrap_metal.tres"),
	preload("res://resources/shell_fragments.tres"),
	preload("res://resources/water_supply.tres"),
]

class DummyScanTarget:
	extends Node2D

	var discovery_id := ""
	var display_name := ""
	var description := ""

	func set_scan_selected(_selected: bool) -> void:
		pass

func _test_discovery_reveal_sync_service(runner) -> void:
	var main := MainScript.new()
	main.blackwater_signal_opportunity = Node2D.new()
	main.blackwater_signal_wash = Polygon2D.new()
	main.blackwater_signal_fleck = Polygon2D.new()
	main.vent_route_hint = Node2D.new()
	main.wreck_signal_hint = Node2D.new()
	main.hidden_glow_plankton = Area2D.new()

	DiscoveryRevealSyncServiceScript.sync_blackwater_signal_opportunity(main, true)
	runner._expect(main.blackwater_signal_opportunity.visible, "visible Blackwater signal opportunity should show the node")
	runner._expect(main.blackwater_signal_wash.color == Color(0.54, 0.72, 1.0, 0.08), "Blackwater signal wash color should stay exact")
	runner._expect(main.blackwater_signal_fleck.color == Color(0.82, 0.94, 1.0, 0.32), "Blackwater signal fleck color should stay exact")

	DiscoveryRevealSyncServiceScript.sync_blackwater_signal_opportunity(main, false)
	runner._expect(not main.blackwater_signal_opportunity.visible, "hidden Blackwater signal opportunity should hide the node")

	main.vent_route_hint.visible = false
	DiscoveryRevealSyncServiceScript.reveal_thermal_vent_route(main)
	runner._expect(main.vent_route_hint.visible, "thermal vent route reveal should show the route hint")

	main.wreck_signal_hint.visible = false
	DiscoveryRevealSyncServiceScript.reveal_pressure_wreck_signal(main)
	runner._expect(main.wreck_signal_hint.visible, "pressure wreck reveal should show the wreck signal hint")

	DiscoveryRevealSyncServiceScript.set_hidden_glow_plankton_active(main, true)
	runner._expect(main.hidden_glow_plankton.visible, "active hidden Glow Plankton should be visible")
	runner._expect(bool(main.hidden_glow_plankton.get("monitoring")), "active hidden Glow Plankton should enable monitoring")

	DiscoveryRevealSyncServiceScript.set_hidden_glow_plankton_active(main, false)
	runner._expect(not main.hidden_glow_plankton.visible, "inactive hidden Glow Plankton should be hidden")
	runner._expect(not bool(main.hidden_glow_plankton.get("monitoring")), "inactive hidden Glow Plankton should disable monitoring")
	main.blackwater_signal_opportunity.free()
	main.blackwater_signal_wash.free()
	main.blackwater_signal_fleck.free()
	main.vent_route_hint.free()
	main.wreck_signal_hint.free()
	main.hidden_glow_plankton.free()
	main.free()

func _test_route_payoff_sync_service(runner) -> void:
	var main := MainScript.new()
	main.blue_chimney_survey_halo = Polygon2D.new()
	main.blue_chimney_survey_gem = Polygon2D.new()
	main.blue_chimney_survey_spark = Polygon2D.new()

	RoutePayoffSyncServiceScript.sync_blue_chimney_payoff(main)
	runner._expect(main.blue_chimney_survey_spark.visible, "active Blue Chimney payoff spark should remain visible")
	runner._expect(main.blue_chimney_survey_gem.color.a >= 0.7, "active Blue Chimney payoff core should stay visible")

	main.run_blue_chimney_draft_reading_recovered = true
	RoutePayoffSyncServiceScript.sync_blue_chimney_payoff(main)
	runner._expect(not main.blue_chimney_survey_spark.visible, "recovered Blue Chimney payoff spark should hide")
	runner._expect(main.blue_chimney_survey_gem.color.a <= 0.2, "recovered Blue Chimney payoff core should dim")
	main.free()

func _test_tool_belt_presenter(runner) -> void:
	runner._expect(ToolBeltPresenterScript.tool_slot_color("ready") == Color(0.018, 0.075, 0.095, 0.5), "ready tool slot color should stay exact")
	runner._expect(ToolBeltPresenterScript.tool_slot_color("locked").a <= 0.36, "locked tool slots should sit quieter than ready tools")
	runner._expect(ToolBeltPresenterScript.tool_slot_color("active").a >= 0.65, "active tool slots should still read as selected")
	runner._expect(ToolBeltPresenterScript.tool_key_color("cooldown") == Color(1.0, 0.82, 0.38, 0.92), "cooldown key color should stay exact")
	runner._expect(ToolBeltPresenterScript.tool_key_color("spent") == ToolBeltPresenterScript.tool_key_color("locked"), "spent and locked key colors should stay visually quiet")
	runner._expect(ToolBeltPresenterScript.tool_icon_color("scanner", "ready") == Color(0.1, 0.92, 1.0, 0.98), "scanner icon color should stay exact")
	runner._expect(ToolBeltPresenterScript.tool_icon_color("decoy", "spent") == Color(0.45, 0.56, 0.62, 0.72), "spent tool icons should use disabled icon color")
	runner._expect(ToolBeltPresenterScript.tool_icon_polygon("scanner").size() > 0, "scanner tool should keep an icon polygon")
	runner._expect(ToolBeltPresenterScript.tool_icon_polygon("burst").size() > 0, "burst tool should keep an icon polygon")
	runner._expect(ToolBeltPresenterScript.tool_icon_polygon("cutter").size() > 0, "cutter tool should keep an icon polygon")
	runner._expect(ToolBeltPresenterScript.tool_icon_polygon("decoy").size() > 0, "decoy tool should keep an icon polygon")
	runner._expect(ToolBeltPresenterScript.tool_icon_polygon("unknown").is_empty(), "unknown tools should not render an icon polygon")
