extends RefCounted

const DiveSessionScript := preload("res://scripts/dive_session.gd")
const ProgressionStateScript := preload("res://scripts/progression_state.gd")
const SurvivalStateScript := preload("res://scripts/survival_state.gd")
const SpawnPointScript := preload("res://scripts/spawn_point.gd")
const UpgradePurchaseScript := preload("res://scripts/upgrade_purchase.gd")
const DiveCapacityServiceScript := preload("res://scripts/services/dive_capacity_service.gd")
const DiveToolActionServiceScript := preload("res://scripts/services/dive_tool_action_service.gd")
const ScanTargetResolverScript := preload("res://scripts/scan_target_resolver.gd")
const SpawnSelectionScript := preload("res://scripts/spawn_selection.gd")
const PlayerScript := preload("res://scripts/player.gd")
const PlayerScene := preload("res://scenes/Player.tscn")
const MainScene := preload("res://scenes/Main.tscn")
const ReadabilityMarkerPatternsScript := preload("res://scripts/readability_marker_patterns.gd")
const ScanPulseVisualScript := preload("res://scripts/scan_pulse_visual.gd")
const ExpeditionGoalFormatterScript := preload("res://scripts/expedition_goal_formatter.gd")
const ExpeditionConditionScript := preload("res://scripts/expedition_condition.gd")
const MainScript := preload("res://scripts/main.gd")
const Area01SourceMapOverlayScript := preload("res://scripts/area01_source_map_overlay.gd")
const Area01BlockoutBuilderScript := preload("res://scripts/area01_blockout_builder.gd")
const Area01SourceTruthValidatorScript := preload("res://scripts/area01_source_truth_validator.gd")
const Area01VisualCueContractScript := preload("res://scripts/area01_visual_cue_contract.gd")
const Area01VisualDirectorScript := preload("res://scripts/area01_visual_director.gd")
const Area01VisualStagingServiceScript := preload("res://scripts/debug/area01_visual_staging_service.gd")
const BlackwaterVisualStagingServiceScript := preload("res://scripts/debug/blackwater_visual_staging_service.gd")
const BlueChimneyVisualStagingServiceScript := preload("res://scripts/debug/blue_chimney_visual_staging_service.gd")
const MobileTouchControlsScript := preload("res://scripts/mobile_touch_controls.gd")
const RunTelemetryResetServiceScript := preload("res://scripts/services/run_telemetry_reset_service.gd")
const ConditionPresenterScript := preload("res://scripts/ui/condition_presenter.gd")
const DaylightCargoVisualStagingServiceScript := preload("res://scripts/debug/daylight_cargo_visual_staging_service.gd")
const DaylightTimerHudServiceScript := preload("res://scripts/ui/daylight_timer_hud_service.gd")
const DepthRailServiceScript := preload("res://scripts/ui/depth_rail_service.gd")
const DiscoveryNamePresenterScript := preload("res://scripts/ui/discovery_name_presenter.gd")
const DuskTrenchVisualStagingServiceScript := preload("res://scripts/debug/dusk_trench_visual_staging_service.gd")
const ExpeditionSlateNodeServiceScript := preload("res://scripts/ui/expedition_slate_node_service.gd")
const ExpeditionSlatePresenterScript := preload("res://scripts/ui/expedition_slate_presenter.gd")
const ExpandedRouteVisualStagingServiceScript := preload("res://scripts/debug/expanded_route_visual_staging_service.gd")
const HealthFeedbackPresenterScript := preload("res://scripts/ui/health_feedback_presenter.gd")
const HealthFeedbackServiceScript := preload("res://scripts/ui/health_feedback_service.gd")
const HealthDamageVisualStagingServiceScript := preload("res://scripts/debug/health_damage_visual_staging_service.gd")
const HollowReefVisualStagingServiceScript := preload("res://scripts/debug/hollow_reef_visual_staging_service.gd")
const HudPromptPresenterScript := preload("res://scripts/ui/hud_prompt_presenter.gd")
const HudPromptStateServiceScript := preload("res://scripts/ui/hud_prompt_state_service.gd")
const HudInstrumentBarServiceScript := preload("res://scripts/ui/hud_instrument_bar_service.gd")
const HudPresenterScript := preload("res://scripts/ui/hud_presenter.gd")
const BlackwaterGatePresenterScript := preload("res://scripts/ui/blackwater_gate_presenter.gd")
const HudLayoutServiceScript := preload("res://scripts/ui/hud_layout_service.gd")
const HudReferenceServiceScript := preload("res://scripts/ui/hud_reference_service.gd")
const SurfaceStatusPresenterScript := preload("res://scripts/ui/surface_status_presenter.gd")
const CargoSlotPresenterScript := preload("res://scripts/ui/cargo_slot_presenter.gd")
const HudVisibilityServiceScript := preload("res://scripts/ui/hud_visibility_service.gd")
const InventorySummaryPresenterScript := preload("res://scripts/ui/inventory_summary_presenter.gd")
const LowerConnectorVisualStagingServiceScript := preload("res://scripts/debug/lower_connector_visual_staging_service.gd")
const MirrorKelpVisualStagingServiceScript := preload("res://scripts/debug/mirror_kelp_visual_staging_service.gd")
const MinimapServiceScript := preload("res://scripts/ui/minimap_service.gd")
const NightBuildPresenterScript := preload("res://scripts/ui/night_build_presenter.gd")
const OpenHatchVisualStagingServiceScript := preload("res://scripts/debug/open_hatch_visual_staging_service.gd")
const OuterShelfVisualStagingServiceScript := preload("res://scripts/debug/outer_shelf_visual_staging_service.gd")
const OxygenFeedbackServiceScript := preload("res://scripts/ui/oxygen_feedback_service.gd")
const ResourcePresenterScript := preload("res://scripts/ui/resource_presenter.gd")
const ResourcePickupPresentationServiceScript := preload("res://scripts/ui/resource_pickup_presentation_service.gd")
const ResourceRoleVisualPresenterScript := preload("res://scripts/ui/resource_role_visual_presenter.gd")
const ResourceSummaryServiceScript := preload("res://scripts/ui/resource_summary_service.gd")
const RecentExpeditionLogServiceScript := preload("res://scripts/ui/recent_expedition_log_service.gd")
const RecentExpeditionPresenterScript := preload("res://scripts/ui/recent_expedition_presenter.gd")
const ScanEffectTextServiceScript := preload("res://scripts/ui/scan_effect_text_service.gd")
const ScanFeedbackPresenterScript := preload("res://scripts/ui/scan_feedback_presenter.gd")
const ScanTargetCardServiceScript := preload("res://scripts/ui/scan_target_card_service.gd")
const ScanTargetFeedbackServiceScript := preload("res://scripts/ui/scan_target_feedback_service.gd")
const SurfaceResultPresenterScript := preload("res://scripts/ui/surface_result_presenter.gd")
const SurfaceRunSummaryServiceScript := preload("res://scripts/ui/surface_run_summary_service.gd")
const SurvivalNeedSummaryServiceScript := preload("res://scripts/ui/survival_need_summary_service.gd")
const SurvivalSupplyCachePresenterScript := preload("res://scripts/ui/survival_supply_cache_presenter.gd")
const SurvivalSupplyCacheStateServiceScript := preload("res://scripts/ui/survival_supply_cache_state_service.gd")
const SurvivalNeedsPanelServiceScript := preload("res://scripts/ui/survival_needs_panel_service.gd")
const ToolBeltPresenterScript := preload("res://scripts/ui/tool_belt_presenter.gd")
const ToolBeltServiceScript := preload("res://scripts/ui/tool_belt_service.gd")
const RouteMemoryPresenterScript := preload("res://scripts/ui/route_memory_presenter.gd")
const RoutePresenterScript := preload("res://scripts/ui/route_presenter.gd")
const RouteProximityServiceScript := preload("res://scripts/services/route_proximity_service.gd")
const RouteSetupServiceScript := preload("res://scripts/services/route_setup_service.gd")
const SceneEventServiceScript := preload("res://scripts/services/scene_event_service.gd")
const SurvivalControllerServiceScript := preload("res://scripts/services/survival_controller_service.gd")
const RouteTimingCuePresenterScript := preload("res://scripts/ui/route_timing_cue_presenter.gd")
const RouteTimingCueServiceScript := preload("res://scripts/ui/route_timing_cue_service.gd")
const RunMemoryStateServiceScript := preload("res://scripts/ui/run_memory_state_service.gd")
const ResearchResultPresenterScript := preload("res://scripts/ui/research_result_presenter.gd")
const ResearchResultCalloutServiceScript := preload("res://scripts/ui/research_result_callout_service.gd")
const ConditionVisualSyncServiceScript := preload("res://scripts/ui/condition_visual_sync_service.gd")
const DiscoveryRevealSyncServiceScript := preload("res://scripts/ui/discovery_reveal_sync_service.gd")
const RouteGateSyncServiceScript := preload("res://scripts/ui/route_gate_sync_service.gd")
const RoutePayoffSyncServiceScript := preload("res://scripts/ui/route_payoff_sync_service.gd")
const RunPanelLayoutServiceScript := preload("res://scripts/ui/run_panel_layout_service.gd")
const RunPanelServiceScript := preload("res://scripts/ui/run_panel_service.gd")
const UpgradeCopyPresenterScript := preload("res://scripts/ui/upgrade_copy_presenter.gd")
const UpgradeMenuServiceScript := preload("res://scripts/ui/upgrade_menu_service.gd")
const UpgradeStateServiceScript := preload("res://scripts/ui/upgrade_state_service.gd")
const SaveServiceScript := preload("res://scripts/services/save_service.gd")
const VisualSmokeBridgeScript := preload("res://scripts/debug/visual_smoke_bridge.gd")
const ShipOffloadVisualStagingServiceScript := preload("res://scripts/debug/ship_offload_visual_staging_service.gd")
const SiltVeinVisualStagingServiceScript := preload("res://scripts/debug/silt_vein_visual_staging_service.gd")
const SurfaceOxygenVisualStagingServiceScript := preload("res://scripts/debug/surface_oxygen_visual_staging_service.gd")
const WideReefVisualStagingServiceScript := preload("res://scripts/debug/wide_reef_visual_staging_service.gd")
const WreckEchoVisualStagingServiceScript := preload("res://scripts/debug/wreck_echo_visual_staging_service.gd")
const ScannableScript := preload("res://scripts/scannable.gd")
const PredatorScript := preload("res://scripts/predator.gd")
const OxygenTankUpgrade := preload("res://resources/upgrades/oxygen_tank_1.tres")
const PressureSealUpgrade := preload("res://resources/upgrades/pressure_seal_1.tres")
const SignalLensUpgrade := preload("res://resources/upgrades/signal_lens_1.tres")
const EchoLensUpgrade := preload("res://resources/upgrades/echo_lens_1.tres")
const ResonanceKeyUpgrade := preload("res://resources/upgrades/resonance_key_1.tres")
const CargoRackUpgrade := preload("res://resources/upgrades/cargo_rack_1.tres")
const WaterFilterUpgrade := preload("res://resources/upgrades/water_filter_1.tres")
const PredatorWarningUpgrade := preload("res://resources/upgrades/predator_warning_1.tres")
const DecoyPulseUpgrade := preload("res://resources/upgrades/decoy_pulse_1.tres")
const SalvageCutterUpgrade := preload("res://resources/upgrades/salvage_cutter_1.tres")
const StarterResourceDefinitions := [
	preload("res://resources/driftwood.tres"),
	preload("res://resources/food_supply.tres"),
	preload("res://resources/glow_plankton.tres"),
	preload("res://resources/kelp_fiber.tres"),
	preload("res://resources/power_supply.tres"),
	preload("res://resources/quartz_glass.tres"),
	preload("res://resources/scrap_metal.tres"),
	preload("res://resources/shell_fragments.tres"),
	preload("res://resources/water_supply.tres"),
]

class DummyScanTarget:
	extends Node2D

	var discovery_id := ""
	var display_name := ""
	var description := ""

	func set_scan_selected(_selected: bool) -> void:
		pass

func _test_monster_research_non_combat_guardrails(runner) -> void:
	var main := MainScript.new()
	main.run_completed_scans = ["gulper_eel"]
	var scan_callout := ResearchResultCalloutServiceScript.format_gulper_research_callout(main)
	runner._expect_no_monster_combat_language(scan_callout, "Gulper scan research")

	main.run_predator_contacts = 1
	var contact_callout := ResearchResultCalloutServiceScript.format_gulper_research_callout(main)
	runner._expect(contact_callout.contains("warning lane"), "contact research should stay framed as route danger")
	runner._expect_no_monster_combat_language(contact_callout, "Gulper contact research")

	main.decoy_pulse_used_this_run = true
	var decoy_callout := ResearchResultCalloutServiceScript.format_gulper_research_callout(main)
	runner._expect(decoy_callout.contains("Decoy timing"), "Monster Research II candidate should stay framed as decoy timing")
	runner._expect_no_monster_combat_language(decoy_callout, "Decoy response research")

	var summary := SurfaceRunSummaryServiceScript.format_run_summary(main, decoy_callout, "extracted")
	runner._expect_no_monster_combat_language(summary, "Monster research result summary")
	runner._expect(not summary.contains("field guide"), "Monster research result should not add field-guide UI language")
	runner._expect(not summary.contains("checklist"), "Monster research result should not add checklist UI language")

	var saved: Dictionary = main.progression_state.to_save_data()
	runner._expect(not saved.has("monster_research"), "Monster Research II planning should not add durable monster research save state")
	runner._expect(not saved.has("creature_inventory"), "Monster Research II planning should not add creature inventory save state")
	main.free()

func _test_echo_lens_result_callout(runner) -> void:
	var main := MainScript.new()

	runner._expect(ResearchResultCalloutServiceScript.format_echo_lens_research_callout(main) == "", "Echo Lens result line should stay hidden until an echo fires")
	main.run_echo_lens_echo_fired = true
	var callout := ResearchResultCalloutServiceScript.format_echo_lens_research_callout(main)
	runner._expect(callout.contains("Echo Lens"), "Echo Lens result line should name the scanner upgrade")
	runner._expect(callout.contains("weak wreck echo below the shelf"), "Echo Lens result line should preserve the broad local echo memory")
	runner._expect_no_echo_lens_locator_language(callout, "Echo Lens result line")
	var summary := SurfaceRunSummaryServiceScript.format_run_summary(main, "%s%s" % [SurfaceRunSummaryServiceScript.format_route_choice_callout(main), callout], "extracted")
	runner._expect(summary.contains("Research:"), "Echo Lens result line should appear as compact research memory")
	runner._expect(not summary.contains("Playtest data:"), "Echo Lens result line should not expose debug telemetry")
	main.free()

func _test_wreck_echo_route_first_pass(runner) -> void:
	var main := MainScript.new()
	runner._expect(not main._wreck_echo_route_available(), "Wreck Echo route should start unavailable")
	main.progression_state.purchased_upgrades[PressureSealUpgrade.id] = true
	runner._expect(not main._wreck_echo_route_available(), "Wreck Echo route should still need Echo Lens I")
	main.progression_state.purchased_upgrades[EchoLensUpgrade.id] = true
	runner._expect(main._wreck_echo_route_available(), "Wreck Echo route should require pressure and Echo Lens context")
	runner._expect(ResearchResultCalloutServiceScript.format_wreck_echo_research_callout(main) == "", "Wreck Echo result line should stay hidden before clue recovery")
	main.run_wreck_echo_clue_recovered = true
	var callout := ResearchResultCalloutServiceScript.format_wreck_echo_research_callout(main)
	runner._expect(callout.contains("Wreck Echo clue"), "Wreck Echo clue should produce compact research callout")
	runner._expect(callout.contains("deeper pressure signal below the shelf"), "Wreck Echo clue should stay broad/local")
	runner._expect_no_echo_lens_locator_language(callout, "Wreck Echo result line")
	var extraction_summary := SurfaceRunSummaryServiceScript.format_extraction_result_summary(main, 0, [])
	runner._expect(extraction_summary.contains("Wreck Echo clue carried"), "Wreck Echo extraction summary should include the clue readback")
	runner._expect(not extraction_summary.contains("%s"), "Wreck Echo extraction summary should not leak string placeholders")
	runner._expect(not extraction_summary.contains("%dm"), "Wreck Echo extraction summary should not leak depth placeholders")
	main._reset_run_telemetry()
	runner._expect(not main.run_wreck_echo_clue_recovered, "Wreck Echo clue should reset between expeditions")
	main.free()

	var main_scene := MainScene.instantiate()
	runner.root.add_child(main_scene)
	var trigger: Area2D = main_scene.get_node("WreckEchoDescent/ClueTrigger")
	runner._expect(not trigger.monitoring, "Wreck Echo trigger should start inactive")
	main_scene.progression_state.purchased_upgrades[PressureSealUpgrade.id] = true
	main_scene.progression_state.purchased_upgrades[EchoLensUpgrade.id] = true
	main_scene.call("_sync_wreck_echo_state")
	runner._expect(trigger.visible, "Wreck Echo trigger should appear when pressure and Echo Lens context are ready")
	runner._expect(trigger.monitoring, "Wreck Echo trigger should listen when available and unrecovered")
	main_scene.run_wreck_echo_clue_recovered = true
	main_scene.call("_sync_wreck_echo_state")
	runner._expect(not trigger.monitoring, "Wreck Echo trigger should disable after clue recovery")

	var presenter_trigger := Area2D.new()
	var presenter_wash := Polygon2D.new()
	var presenter_rib_a := Polygon2D.new()
	var presenter_rib_b := Polygon2D.new()
	var presenter_core := Polygon2D.new()
	var presenter_marker_outer := Polygon2D.new()
	var presenter_marker_inner := Polygon2D.new()
	var presenter_markers: Array[Polygon2D] = [presenter_marker_outer, presenter_marker_inner]
	RoutePresenterScript.sync_wreck_echo_state(presenter_trigger, presenter_wash, presenter_rib_a, presenter_rib_b, presenter_core, presenter_markers, true, false)
	runner._expect(presenter_trigger.visible and presenter_trigger.monitoring and presenter_trigger.monitorable, "route presenter should enable Wreck Echo trigger for available unrecovered route")
	runner._expect(presenter_core.visible and presenter_marker_outer.visible, "route presenter should show clue visuals for available route")
	RoutePresenterScript.sync_wreck_echo_state(presenter_trigger, presenter_wash, presenter_rib_a, presenter_rib_b, presenter_core, presenter_markers, true, true)
	runner._expect(not presenter_trigger.monitoring, "route presenter should disable recovered Wreck Echo trigger")
	runner._expect(presenter_marker_outer.color.a < presenter_marker_inner.color.a, "route presenter should keep recovered marker colors quiet but layered")
	var payoff_halo := Polygon2D.new()
	var payoff_core := Polygon2D.new()
	var payoff_spark := Polygon2D.new()
	RoutePresenterScript.sync_blackwater_trace_payoff(payoff_halo, payoff_core, payoff_spark, false)
	runner._expect(payoff_halo.color.a > 0.3 and payoff_core.color.a > 0.8, "route presenter should show unrecovered payoff cores clearly")
	runner._expect(payoff_spark.visible and payoff_spark.color.a > 0.8, "route presenter should show unrecovered payoff sparks")
	RoutePresenterScript.sync_blackwater_trace_payoff(payoff_halo, payoff_core, payoff_spark, true)
	runner._expect(payoff_halo.color.a < 0.1 and payoff_core.color.a < 0.2, "route presenter should quiet recovered payoff cores")
	runner._expect(not payoff_spark.visible, "route presenter should hide recovered payoff sparks")
	RoutePresenterScript.sync_east_shelf_pocket_payoff(payoff_halo, payoff_core, payoff_spark, false)
	runner._expect(payoff_halo.color.a > 0.3 and payoff_core.color.g >= 1.0, "route presenter should show East Shelf payoff core brightly before recovery")
	RoutePresenterScript.sync_blue_chimney_payoff(payoff_halo, payoff_core, payoff_spark, true)
	runner._expect(payoff_halo.color.a < 0.1 and not payoff_spark.visible, "route presenter should quiet Blue Chimney payoff after recovery")
	var hatch_shimmer := Polygon2D.new()
	var hatch_badge := Polygon2D.new()
	var hatch_label := Label.new()
	var hatch_bars := Polygon2D.new()
	RoutePresenterScript.sync_sealed_shelf_hatch_state(hatch_shimmer, hatch_badge, hatch_label, hatch_bars, false, false)
	runner._expect(hatch_label.text == "ECHO LOCK", "route presenter should show sealed shelf echo lock before lens context")
	RoutePresenterScript.sync_sealed_shelf_hatch_state(hatch_shimmer, hatch_badge, hatch_label, hatch_bars, true, true)
	runner._expect(hatch_label.text == "OPEN" and hatch_badge.color.a > 0.7, "route presenter should show sealed shelf open state with key ownership")
	var salvage_hatch := Polygon2D.new()
	var salvage_lock := Polygon2D.new()
	var salvage_glint := Polygon2D.new()
	var salvage_tool := Label.new()
	var salvage_promise := Label.new()
	var salvage_lane := Node2D.new()
	RoutePresenterScript.sync_salvage_pocket_open_state(salvage_hatch, salvage_lock, salvage_glint, salvage_tool, salvage_promise, salvage_lane, false)
	runner._expect(not salvage_lane.visible and salvage_tool.text == "CUTTER NEEDED", "route presenter should keep salvage pocket sealed before cutter ownership")
	RoutePresenterScript.sync_salvage_pocket_open_state(salvage_hatch, salvage_lock, salvage_glint, salvage_tool, salvage_promise, salvage_lane, true)
	runner._expect(salvage_lane.visible and salvage_tool.text == "CUTTER READY" and salvage_promise.text == "OPEN", "route presenter should show salvage pocket open state with cutter ownership")
	var gate_mouth := Polygon2D.new()
	var gate_wash := Polygon2D.new()
	var gate_lip := Polygon2D.new()
	var gate_badge := Polygon2D.new()
	var gate_label := Label.new()
	var gate_shard := Polygon2D.new()
	var gate_sill := Node2D.new()
	var gate_return := Polygon2D.new()
	RoutePresenterScript.sync_blackwater_crack_gate_state(gate_mouth, gate_wash, gate_lip, gate_badge, gate_label, gate_shard, gate_sill, gate_return, false, false)
	runner._expect(gate_label.text == "RESONANCE SEAL" and not gate_sill.visible, "route presenter should show sealed Blackwater state before key path")
	RoutePresenterScript.sync_blackwater_crack_gate_state(gate_mouth, gate_wash, gate_lip, gate_badge, gate_label, gate_shard, gate_sill, gate_return, true, true)
	runner._expect(gate_label.text == "KEY READY" and gate_sill.visible and gate_return.color.a > 0.1, "route presenter should show Blackwater open state with resonance key")
	var pressure_boundary := Area2D.new()
	var pressure_shimmer := Polygon2D.new()
	var pressure_top := Polygon2D.new()
	var pressure_bottom := Polygon2D.new()
	var pressure_bar_a := Polygon2D.new()
	var pressure_bar_b := Polygon2D.new()
	var pressure_bar_c := Polygon2D.new()
	var pressure_left := Polygon2D.new()
	var pressure_right := Polygon2D.new()
	var pressure_badge := Polygon2D.new()
	var pressure_label := Label.new()
	RoutePresenterScript.sync_pressure_lock_state(pressure_boundary, pressure_shimmer, pressure_top, pressure_bottom, pressure_bar_a, pressure_bar_b, pressure_bar_c, pressure_left, pressure_right, pressure_badge, pressure_label, false)
	runner._expect(pressure_boundary.monitoring and pressure_boundary.monitorable and pressure_label.text == "LOCKED", "route presenter should block pressure gate before seal ownership")
	RoutePresenterScript.sync_pressure_lock_state(pressure_boundary, pressure_shimmer, pressure_top, pressure_bottom, pressure_bar_a, pressure_bar_b, pressure_bar_c, pressure_left, pressure_right, pressure_badge, pressure_label, true)
	runner._expect(not pressure_boundary.monitoring and not pressure_boundary.monitorable and pressure_label.text == "OPEN", "route presenter should open pressure gate after seal ownership")
	runner._expect(pressure_badge.color.g > pressure_badge.color.r, "route presenter should keep open pressure gate green")
	presenter_trigger.free()
	presenter_wash.free()
	presenter_rib_a.free()
	presenter_rib_b.free()
	presenter_core.free()
	presenter_marker_outer.free()
	presenter_marker_inner.free()
	payoff_halo.free()
	payoff_core.free()
	payoff_spark.free()
	hatch_shimmer.free()
	hatch_badge.free()
	hatch_label.free()
	hatch_bars.free()
	salvage_hatch.free()
	salvage_lock.free()
	salvage_glint.free()
	salvage_tool.free()
	salvage_promise.free()
	salvage_lane.free()
	gate_mouth.free()
	gate_wash.free()
	gate_lip.free()
	gate_badge.free()
	gate_label.free()
	gate_shard.free()
	gate_sill.free()
	gate_return.free()
	pressure_boundary.free()
	pressure_shimmer.free()
	pressure_top.free()
	pressure_bottom.free()
	pressure_bar_a.free()
	pressure_bar_b.free()
	pressure_bar_c.free()
	pressure_left.free()
	pressure_right.free()
	pressure_badge.free()
	pressure_label.free()
	main_scene.queue_free()

func _test_east_shelf_pocket_result_callout(runner) -> void:
	var main := MainScript.new()
	runner._expect(ResearchResultCalloutServiceScript.format_east_shelf_pocket_research_callout(main) == "", "East Shelf pocket result line should stay hidden before signal-core recovery")

	main.run_east_shelf_pocket_ping_recovered = true
	var callout := ResearchResultCalloutServiceScript.format_east_shelf_pocket_research_callout(main)
	runner._expect(callout.contains("East Shelf signal core"), "East Shelf signal core should produce compact research memory")
	runner._expect(callout.contains("sealed route below the arch"), "East Shelf pocket result line should stay broad and local")
	runner._expect(not callout.to_lower().contains("map"), "East Shelf pocket result line should not imply a map marker")
	runner._expect(not callout.to_lower().contains("quest"), "East Shelf pocket result line should not imply quest UI")
	runner._expect(not callout.to_lower().contains("checklist"), "East Shelf pocket result line should not imply checklist UI")

	var extraction_summary := SurfaceRunSummaryServiceScript.format_extraction_result_summary(main, 0, [])
	runner._expect(extraction_summary.contains("East Shelf signal core"), "East Shelf pocket extraction summary should include recovered signal-core memory")
	runner._expect(not extraction_summary.contains("%s"), "East Shelf pocket extraction summary should not leak string placeholders")
	var saved: Dictionary = main.progression_state.to_save_data()
	runner._expect(not saved.has("east_shelf_pocket_signal_core"), "East Shelf signal core should not become durable save data")
	runner._expect(not saved.has("east_shelf_routes"), "East Shelf signal core should not create durable route state")
	main.free()

func _test_lower_connector_echo_opportunity(runner) -> void:
	var main := MainScene.instantiate()
	main.status_label = Label.new()
	main.dive_session.start()
	main.dive_session.has_left_base = true
	main.player_near_lower_connector_echo = true
	var prompt: String = main.call("_format_hud_prompt")
	runner._expect(prompt.contains("Drop Echo"), "Lower connector proximity should own the active dive prompt")
	runner._expect(prompt.contains("lower-route ping"), "Drop Echo prompt should explain the narrow research opportunity")

	var handled: bool = main.call("_try_lower_connector_echo_interaction")
	runner._expect(handled, "Drop Echo should handle interact while the player is nearby during a dive")
	runner._expect(main.run_lower_connector_echo_recovered, "Drop Echo interaction should record one run-scoped research ping")
	if main.status_label != null:
		runner._expect(main.status_label.text.contains("Return safely"), "Drop Echo interaction should preserve extraction pressure")

	var repeat_handled: bool = main.call("_try_lower_connector_echo_interaction")
	runner._expect(repeat_handled, "Drop Echo should keep handling repeat interact while nearby")
	if main.status_label != null:
		runner._expect(main.status_label.text.contains("already recorded"), "Drop Echo repeat interaction should not duplicate the payoff")

	main.player_near_lower_connector_echo = false
	var not_handled: bool = main.call("_try_lower_connector_echo_interaction")
	runner._expect(not not_handled, "Drop Echo should not consume interact outside its proximity zone")

	var callout: String = ResearchResultCalloutServiceScript.format_lower_connector_echo_research_callout(main)
	runner._expect(callout.contains("Drop Echo"), "Drop Echo should produce compact extraction research memory")
	runner._expect(callout.contains("Shelf Drop Connector"), "Drop Echo result memory should name the lower connector")
	runner._expect(not callout.to_lower().contains("map"), "Drop Echo result line should not imply map UI")
	runner._expect(not callout.to_lower().contains("quest"), "Drop Echo result line should not imply quest UI")
	runner._expect(not callout.to_lower().contains("checklist"), "Drop Echo result line should not imply checklist UI")

	var empty_cargo: Array[String] = []
	var extraction_summary: String = SurfaceRunSummaryServiceScript.format_extraction_result_summary(main, 0, empty_cargo)
	runner._expect(extraction_summary.contains("Drop Echo"), "Drop Echo extraction summary should include recovered lower-route memory")
	var saved: Dictionary = main.progression_state.to_save_data()
	runner._expect(not saved.has("drop_echo"), "Drop Echo should not become durable save data")
	runner._expect(not saved.has("lower_connector_echo"), "Drop Echo should not create durable route state")

	main.call("_reset_run_telemetry")
	runner._expect(not main.run_lower_connector_echo_recovered, "Drop Echo research ping should reset between expeditions")
	main.free()
